import { createFileRoute } from "@tanstack/react-router";
import { Send, RefreshCw, Paperclip, Bot, User, Database } from "lucide-react";
import { useState } from "react";
import { motion } from "framer-motion";
import { cn } from "@/lib/utils";

export const Route = createFileRoute("/agent/rag")({
  component: RAGPage,
});

type Message = {
  id: string;
  role: "user" | "assistant";
  content: string;
  sources?: { name: string; relevance: number }[];
};

const mockHistory: Message[] = [
  {
    id: "1",
    role: "user",
    content: "Why is the lining failing on Furnace 3?",
  },
  {
    id: "2",
    role: "assistant",
    content:
      "Based on the live twin state, Furnace 3 is experiencing a high thermal gradient. According to the maintenance logs, the last refractory lining replacement was 14 weeks ago (exceeding the standard 12-week cycle). The vibration anomaly detected at 14:48:02 correlates with lining wear.",
    sources: [
      { name: "Furnace 3 Manual p.4-3", relevance: 94 },
      { name: "Incident Report Sept 2025", relevance: 89 },
      { name: "SOP v2.3 p.7", relevance: 83 },
    ],
  },
];

function RAGPage() {
  const [messages, setMessages] = useState<Message[]>(mockHistory);
  const [input, setInput] = useState("");
  const [isTyping, setIsTyping] = useState(false);

  const handleSend = (e: React.FormEvent) => {
    e.preventDefault();
    if (!input.trim()) return;

    const userMsg: Message = {
      id: Date.now().toString(),
      role: "user",
      content: input,
    };
    
    setMessages((prev) => [...prev, userMsg]);
    setInput("");
    setIsTyping(true);

    // Mock API response delay
    setTimeout(() => {
      setIsTyping(false);
      setMessages((prev) => [
        ...prev,
        {
          id: (Date.now() + 1).toString(),
          role: "assistant",
          content: "This is a simulated response. In production, this would be generated by Llama 3 grounded in live twin data and retrieved documents via the backend /api/rag/ask endpoint.",
        },
      ]);
    }, 1500);
  };

  return (
    <div className="mx-auto flex h-[calc(100vh-4rem)] max-w-4xl flex-col px-4 py-6 md:px-8">
      {/* Header */}
      <div className="mb-6 flex items-center justify-between border-b border-border pb-4">
        <div className="flex items-center gap-2">
          <div className="flex size-8 items-center justify-center rounded bg-primary/20 text-primary">
            <MessageSquareIcon className="size-4" />
          </div>
          <div>
            <h1 className="text-lg font-semibold tracking-tight">NEXUS Assistant</h1>
            <p className="text-xs text-muted-foreground">RAG-powered interactive agent</p>
          </div>
        </div>
        <button
          onClick={() => setMessages([])}
          className="flex items-center gap-2 rounded-md border border-border bg-background px-3 py-1.5 text-xs font-medium text-muted-foreground transition-colors hover:bg-accent hover:text-foreground"
        >
          <RefreshCw className="size-3.5" />
          New Conversation
        </button>
      </div>

      {/* Context Bar */}
      <div className="mb-6 flex items-center gap-4 rounded-lg border border-border bg-card/50 p-3 text-sm text-muted-foreground">
        <Database className="size-4 text-primary" />
        <span className="font-medium text-foreground">Context:</span>
        <div className="flex items-center gap-2">
          <span className="rounded bg-secondary px-2 py-0.5">Furnace 3</span>
          <span className="rounded bg-secondary px-2 py-0.5">Batch: CB-001</span>
          <span className="flex items-center gap-1.5 rounded bg-secondary px-2 py-0.5">
            Status: <span className="flex size-2 rounded-full bg-destructive"></span>
          </span>
        </div>
      </div>

      {/* Chat Area */}
      <div className="flex-1 space-y-6 overflow-y-auto pr-4 scrollbar-thin">
        {messages.map((msg) => (
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            key={msg.id}
            className={cn("flex gap-4", msg.role === "user" ? "justify-end" : "justify-start")}
          >
            {msg.role === "assistant" && (
              <div className="flex size-8 shrink-0 items-center justify-center rounded-full bg-primary/10 text-primary">
                <Bot className="size-4" />
              </div>
            )}
            
            <div
              className={cn(
                "max-w-[80%] space-y-3 rounded-2xl px-5 py-4",
                msg.role === "user"
                  ? "bg-primary text-primary-foreground"
                  : "bg-secondary text-secondary-foreground"
              )}
            >
              <div className="text-sm leading-relaxed">{msg.content}</div>

              {msg.sources && msg.sources.length > 0 && (
                <div className="mt-4 rounded-xl border border-border/50 bg-background/50 p-3">
                  <div className="mb-2 flex items-center gap-1.5 text-xs font-semibold text-muted-foreground">
                    <Paperclip className="size-3" />
                    Sources
                  </div>
                  <ul className="space-y-1.5">
                    {msg.sources.map((src, i) => (
                      <li key={i} className="flex items-center justify-between text-xs">
                        <span className="flex items-center gap-1.5 text-foreground/80">
                          <span className="size-1 rounded-full bg-primary/50" />
                          {src.name}
                        </span>
                        <span className="text-muted-foreground">{src.relevance}%</span>
                      </li>
                    ))}
                  </ul>
                </div>
              )}
            </div>

            {msg.role === "user" && (
              <div className="flex size-8 shrink-0 items-center justify-center rounded-full bg-accent text-muted-foreground">
                <User className="size-4" />
              </div>
            )}
          </motion.div>
        ))}
        
        {isTyping && (
          <div className="flex gap-4">
            <div className="flex size-8 shrink-0 items-center justify-center rounded-full bg-primary/10 text-primary">
              <Bot className="size-4" />
            </div>
            <div className="flex items-center gap-1 rounded-2xl bg-secondary px-5 py-4">
              <div className="size-1.5 animate-bounce rounded-full bg-muted-foreground" style={{ animationDelay: "0ms" }} />
              <div className="size-1.5 animate-bounce rounded-full bg-muted-foreground" style={{ animationDelay: "150ms" }} />
              <div className="size-1.5 animate-bounce rounded-full bg-muted-foreground" style={{ animationDelay: "300ms" }} />
            </div>
          </div>
        )}
      </div>

      {/* Input Area */}
      <form onSubmit={handleSend} className="mt-4 pt-4">
        <div className="relative flex items-center">
          <input
            type="text"
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder="Ask a question about the process or manuals..."
            className="w-full rounded-full border border-border bg-card py-3 pl-5 pr-14 text-sm outline-none transition-colors focus:border-primary/50"
          />
          <button
            type="submit"
            disabled={!input.trim()}
            className="absolute right-2 flex size-8 items-center justify-center rounded-full bg-primary text-primary-foreground transition-opacity disabled:opacity-50"
          >
            <Send className="size-4" />
          </button>
        </div>
      </form>
    </div>
  );
}

// Missing import mock
function MessageSquareIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z" />
    </svg>
  );
}
