/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as AgentIndexRouteImport } from './routes/agent.index'
import { Route as AgentPinnRouteImport } from './routes/agent.pinn'
import { Route as AgentRagRouteImport } from './routes/agent.rag'
import { Route as TwinsTwinRouteImport } from './routes/twins.$twin'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentIndexRoute = AgentIndexRouteImport.update({
  id: '/agent/',
  path: '/agent/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentPinnRoute = AgentPinnRouteImport.update({
  id: '/agent/pinn',
  path: '/agent/pinn',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRagRoute = AgentRagRouteImport.update({
  id: '/agent/rag',
  path: '/agent/rag',
  getParentRoute: () => rootRouteImport,
} as any)
const TwinsTwinRoute = TwinsTwinRouteImport.update({
  id: '/twins/$twin',
  path: '/twins/$twin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/agent/pinn': typeof AgentPinnRoute
  '/agent/rag': typeof AgentRagRoute
  '/twins/$twin': typeof TwinsTwinRoute
  '/agent/': typeof AgentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/agent/pinn': typeof AgentPinnRoute
  '/agent/rag': typeof AgentRagRoute
  '/twins/$twin': typeof TwinsTwinRoute
  '/agent': typeof AgentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/dashboard': typeof DashboardRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/agent/pinn': typeof AgentPinnRoute
  '/agent/rag': typeof AgentRagRoute
  '/twins/$twin': typeof TwinsTwinRoute
  '/agent/': typeof AgentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/notifications'
    | '/profile'
    | '/agent/pinn'
    | '/agent/rag'
    | '/twins/$twin'
    | '/agent/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/notifications'
    | '/profile'
    | '/agent/pinn'
    | '/agent/rag'
    | '/twins/$twin'
    | '/agent'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/dashboard'
    | '/notifications'
    | '/profile'
    | '/agent/pinn'
    | '/agent/rag'
    | '/twins/$twin'
    | '/agent/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  DashboardRoute: typeof DashboardRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  AgentPinnRoute: typeof AgentPinnRoute
  AgentRagRoute: typeof AgentRagRoute
  TwinsTwinRoute: typeof TwinsTwinRoute
  AgentIndexRoute: typeof AgentIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/': {
      id: '/agent/'
      path: '/agent'
      fullPath: '/agent/'
      preLoaderRoute: typeof AgentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/pinn': {
      id: '/agent/pinn'
      path: '/agent/pinn'
      fullPath: '/agent/pinn'
      preLoaderRoute: typeof AgentPinnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent/rag': {
      id: '/agent/rag'
      path: '/agent/rag'
      fullPath: '/agent/rag'
      preLoaderRoute: typeof AgentRagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/twins/$twin': {
      id: '/twins/$twin'
      path: '/twins/$twin'
      fullPath: '/twins/$twin'
      preLoaderRoute: typeof TwinsTwinRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  DashboardRoute: DashboardRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  AgentPinnRoute: AgentPinnRoute,
  AgentRagRoute: AgentRagRoute,
  TwinsTwinRoute: TwinsTwinRoute,
  AgentIndexRoute: AgentIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
